name: Build and release Aseprite (macOS Intel)

on:
  push:
    branches:
      - main
    paths:
      - 'BuildLog.md'
  workflow_dispatch:
env:
  BUILD_TYPE: Release

jobs:
  fetch-aseprite-info:
    name: Fetch deps info
    runs-on: ubuntu-latest
    outputs:
      download-link: ${{ steps.aseprite-link.outputs.download-link }}
      release-tag: ${{ steps.aseprite-link.outputs.release-tag }}
    steps:
      - name: Fetch Aseprite release link
        id: aseprite-link
        uses: a1393323447/fetch-release@main
        with:
          group: aseprite
          repo: aseprite
          match: Aseprite-.*?-Source.zip

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: fetch-aseprite-info
    permissions:
      contents: write
    outputs:
      download-link: ${{ needs.fetch-aseprite-info.outputs.download-link }}
      release-tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.fetch-aseprite-info.outputs.release-tag }}
          body: Aseprite-${{ needs.fetch-aseprite-info.outputs.release-tag }}
          skipIfReleaseExists: true
          token: ${{ secrets.GITHUB_TOKEN }}

  build-aseprite:
    name: Build Aseprite (macOS Intel)
    needs: create-release
    permissions:
      contents: write
    runs-on: macos-12.xlarge  # 关键修改：强制使用 Intel 芯片运行器
    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          brew update
          brew install cmake ninja wget

      - name: Clone Aseprite
        run: |
          git clone --recurse-submodules -j8 https://github.com/aseprite/aseprite --branch ${{ needs.create-release.outputs.release-tag }}

      - name: Install Skia (macOS x64)
        working-directory: aseprite
        run: |
          wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-macOS-Release-x64.zip
          unzip Skia-macOS-Release-x64.zip -d skia

      - name: Generate Build Files
        working-directory: aseprite
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 \
            -DCMAKE_OSX_ARCHITECTURES=x86_64 \  # 关键架构指定
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=ON \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=$(pwd)/skia \
            -DSKIA_LIBRARY_DIR=$(pwd)/skia/out/Release-x64

      - name: Compile Aseprite
        working-directory: aseprite/build
        run: ninja

      - name: Package Artifacts
        working-directory: aseprite/build/bin
        run: |
          # 创建便携版配置文件
          echo '# Portable configuration' > aseprite.ini
          # 打包成 zip
          zip -r Aseprite-${{ needs.create-release.outputs.release-tag }}-macOS-Intel.zip *

      - name: Upload Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: aseprite/build/bin/Aseprite-${{ needs.create-release.outputs.release-tag }}-macOS-Intel.zip
          asset_name: Aseprite-${{ needs.create-release.outputs.release-tag }}-macOS-Intel.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
          overwrite: true
